import { PATH_GLIDE_DURATION_MS } from '../../lib/animations/lilaMotion';

export const TRANSITION_TRAVEL_MS = PATH_GLIDE_DURATION_MS;
export const TRANSITION_POST_HOLD_MS = 380;
export const TRANSITION_FADE_OUT_MS = 240;
export const TRANSITION_TOTAL_MS =
  TRANSITION_TRAVEL_MS + TRANSITION_POST_HOLD_MS + TRANSITION_FADE_OUT_MS;
